### ISSUE TITLE
Build error when importing jtreemap:1.1.3 and building on JDK 17

### ISSUE THREAD

**Issue by gtoison** [Appendium/jtreemap#15]
Hello,
First of all thank you for providing and maintaining jtreemap!
I am trying updating from `sourceforge.net:jtreemap:1.1.0` to `net.sf.jtreemap:jtreemap:1.1.3` and running into an issue because the newer version has a dependency on lombok.
I am compiling on JDK 17 and it looks like adding lombok on the classpath is enough to trigger the annotation processing (even if there are no lombok annotations in my sources).
The issue looks a lot like this [StackOverFlow](https://stackoverflow.com/questions/68330987/module-jdk-compiler-does-not-opens-com-sun-tools-javac-processing-to-unnamed-m) question and the problem seems to be solved in newer lombok versions.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:compile (default-compile) on project pilot-jar: Fatal error compiling: java.lang.ExceptionInInitializerError: Unable to make field private com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs accessible: module jdk.compiler does not "opens com.sun.tools.javac.processing" to unnamed module @258a8227
```

Would you consider removing lombok to prevent possible future compatibility issues? From what I have seen only a few classes seem to be using it. I can try making a Pull Request if you're open to external contributions

**Comment by benoitx** [comment]
I would gratefully accept a pull request.Thank youBenoît -----Important NoticeThis communication contains information that is consideredconfidential and may also be privileged. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s) please note that any form of distribution, copying or use of this communication or theinformation in it is strictly prohibited and may be unlawful. If you have received this communication in error please return it to the sender anddelete the originalOn 5 Feb 2024, at 14:33, Guillaume Toison ***@***.***> wrote:﻿
Hello,
First of all thank you for providing and maintaining jtreemap!
I am trying updating from sourceforge.net:jtreemap:1.1.0 to net.sf.jtreemap:jtreemap:1.1.3 and running into an issue because the newer version has a dependency on lombok.
I am compiling on JDK 17 and it looks like adding lombok on the classpath is enough to trigger the annotation processing (even if there are no lombok annotations in my sources).
The issue looks a lot like this StackOverFlow question and the problem seems to be solved in newer lombok versions.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:compile (default-compile) on project pilot-jar: Fatal error compiling: java.lang.ExceptionInInitializerError: Unable to make field private com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs accessible: module jdk.compiler does not "opens com.sun.tools.javac.processing" to unnamed module @258a8227

Would you consider removing lombok to prevent possible future compatibility issues? From what I have seen only a few classes seem to be using it. I can try making a Pull Request if you're open to external contributions
